apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynodejs-app
  template:
    metadata:
      labels:
        app: mynodejs-app
    spec:
      containers:
      - name: mynodejs-app
        image: nahid0002/cicd-nexus-sonarqube:latest
        ports:
        - containerPort: 8080
